# Generated by Django 5.1.4 on 2025-01-17 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_hash', models.CharField(max_length=16, unique=True)),
                ('access_token', models.CharField(max_length=128)),
                ('scope', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeusers', to='app.store')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreData',
        ),
        migrations.AddField(
            model_name='storeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeusers', to='app.user'),
        ),
    ]
